services:
  postgres_primary:
    build: 
      context: ./primary
      dockerfile: Dockerfile
      args:
        POSTGRES_USER: "${POSTGRES_PRIMARY_USER}"
        POSTGRES_PASSWORD: "${POSTGRES_PRIMARY_PASSWORD}"
        POSTGRES_DB: "${POSTGRES_DB}"
        POSTGRES_SECONDARY_USER: "${POSTGRES_SECONDARY_USER}"
    container_name: postgres_primary
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_PRIMARY_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PRIMARY_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_primary_data:/var/lib/postgresql/data
    networks:
      - postgres_network

  postgres_secondary:
    build: 
      context: ./secondary
      dockerfile: Dockerfile
      args:
        POSTGRES_USER: "${POSTGRES_SECONDARY_USER}"
        POSTGRES_PASSWORD: "${POSTGRES_SECONDARY_PASSWORD}"
        POSTGRES_DB: "${POSTGRES_DB}"
        POSTGRES_PRIMARY_USER: "${POSTGRES_PRIMARY_USER}"
    container_name: postgres_secondary
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_SECONDARY_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_SECONDARY_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - postgres_secondary_data:/var/lib/postgresql/data
    networks:
      - postgres_network
    depends_on:
      - postgres_primary

volumes:
  postgres_primary_data: {}
  postgres_secondary_data: {}

networks:
  postgres_network:
    driver: bridge
