ALTER SYSTEM SET password_encryption = 'scram-sha-256';

CREATE ROLE ${POSTGRES_PRIMARY_USER} WITH LOGIN PASSWORD '${POSTGRES_PRIMARY_PASSWORD}';
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_PRIMARY_USER};
GRANT USAGE, SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${POSTGRES_PRIMARY_USER};

CREATE ROLE ${POSTGRES_SECONDARY_USER} WITH LOGIN PASSWORD '${POSTGRES_SECONDARY_PASSWORD}' REPLICATION;
