ALTER SYSTEM SET password_encryption = 'scram-sha-256';

CREATE ROLE ${POSTGRES_APP_USER} WITH LOGIN PASSWORD '${POSTGRES_APP_PASSWORD}';
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_APP_USER};
GRANT USAGE, SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${POSTGRES_APP_USER};

CREATE ROLE ${POSTGRES_REPLICATOR_USER} WITH LOGIN PASSWORD '${POSTGRES_REPLICATOR_PASSWORD}' REPLICATION;
